In [2]:
print("=" * 60)
print("🚀 AI Customer Intelligence Platform")
print("=" * 60)

============================================================
🚀 AI Customer Intelligence Platform
============================================================

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

print("Pandas :", pd.__version__)
print("NumPy :", np.__version__)

Pandas : 2.3.3
NumPy : 2.2.6

In [4]:
PROJECT_NAME = "AI Customer Intelligence Platform"

print(PROJECT_NAME)

AI Customer Intelligence Platform

# Customer Dataset Design

The Customers table stores all customer-related information required for analytics, machine learning, and business intelligence.

In [5]:
customer_columns = [
    "customer_id",
    "first_name",
    "last_name",
    "gender",
    "age",
    "email",
    "phone",
    "city",
    "state",
    "country",
    "signup_date",
    "customer_segment",
    "annual_income",
    "marital_status",
    "occupation",
    "loyalty_points",
    "is_active"
]

print(customer_columns)

['customer_id', 'first_name', 'last_name', 'gender', 'age', 'email', 'phone', 'city', 'state', 'country', 'signup_date', 'customer_segment', 'annual_income', 'marital_status', 'occupation', 'loyalty_points', 'is_active']

In [6]:
from faker import Faker

fake = Faker()

print(fake.name())
print(fake.city())
print(fake.email())

Amy Bean
Shahborough
oscar71@example.org

In [7]:
import sys
print(sys.executable)

c:\Users\Monika\OneDrive\Desktop\AI-Customer-Intelligence-Platform\venv\Scripts\python.exe

In [8]:
import pandas as pd
import numpy as np
from faker import Faker
import random

In [9]:
PROJECT_NAME = "AI Customer Intelligence Platform"
PROJECT_VERSION = "1.0"

print(f"Project : {PROJECT_NAME}")
print(f"Version : {PROJECT_VERSION}")

Project : AI Customer Intelligence Platform
Version : 1.0

In [10]:
from faker import Faker 
import random 
fake = Faker("en_IN")
random.seed(42)
Faker.seed(42)
print("Faker initialized successfully!")

Faker initialized successfully!

In [14]:
NUM_CUSTOMERS = 1000
customer_segments = [
    "Premium",
    "GOld",
    "Silver",
    "Regular"
]
occupations = [
    "Software Engineer",
    "Doctor",
    "Teacher",
    "Business",
    "Student",
    "Lawyer",
    "Designer",
    "Manager",
    "Data Analyst",
    "Accountant"
]
marital_status = [
    "Single",
    "Married"
]
print("Configuration Loaded Successfully!")
print(f"Customer to Generate : {NUM_CUSTOMERS}")

Configuration Loaded Successfully!
Customer to Generate : 1000

In [15]:
def generate_customer(customer_id):

    customer = {
        "customer_id": customer_id,
        "first_name": fake.first_name(),
        "last_name": fake.last_name(),
        "gender": random.choice(["Male", "Female"]),
        "age": random.randint(18, 70),
        "email": fake.email(),
        "phone": fake.phone_number(),
        "city": fake.city(),
        "state": fake.state(),
        "country": "India",
        "signup_date": fake.date_between(start_date="-5y", end_date="today"),
        "customer_segment": random.choice(customer_segments),
        "annual_income": random.randint(200000, 3000000),
        "marital_status": random.choice(marital_status),
        "occupation": random.choice(occupations),
        "loyalty_points": random.randint(0, 10000),
        "is_active": random.choice([True, False])
    }

    return customer

In [16]:
customer = generate_customer(1)

customer

{'customer_id': 1,
 'first_name': 'Oni',
 'last_name': 'Kannan',
 'gender': 'Male',
 'age': 65,
 'email': 'zmall@example.org',
 'phone': '+916542351161',
 'city': 'Hapur',
 'state': 'Punjab',
 'country': 'India',
 'signup_date': datetime.date(2023, 10, 25),
 'customer_segment': 'Premium',
 'annual_income': 2487433,
 'marital_status': 'Single',
 'occupation': 'Accountant',
 'loyalty_points': 6912,
 'is_active': True}

In [17]:
customers = []

for customer_id in range(1, NUM_CUSTOMERS + 1):
    customers.append(generate_customer(customer_id))

print(f"Total Customers Generated: {len(customers)}")

Total Customers Generated: 1000

In [18]:
customers_df = pd.DataFrame(customers)
customers_df.head()

,customer_id,first_name,last_name,gender,age,email,phone,city,state,country,signup_date,customer_segment,annual_income,marital_status,occupation,loyalty_points,is_active
0,1,Caleb,Sharaf,Male,23,radhakrishnanfarhan@example.net,09593103413,Nadiad,Himachal Pradesh,India,2025-06-03,GOld,1175850,Single,Data Analyst,3257,False
1,2,Janya,Gaba,Male,46,isha34@example.net,1928327648,Anantapur,Uttarakhand,India,2022-01-15,Silver,227257,Single,Designer,5574,False
2,3,Veer,Balay,Male,31,nandini41@example.org,5376724238,Bhimavaram,Maharashtra,India,2026-07-12,Silver,628700,Single,Designer,1584,False
3,4,Mohini,Pathak,Female,56,lakshitupadhyay@example.com,+910122691669,Dehri,Himachal Pradesh,India,2026-04-09,Silver,382244,Married,Data Analyst,2045,False
4,5,Advay,Contractor,Male,53,harini14@example.com,+917048281489,Jamnagar,Kerala,India,2022-12-09,Silver,2836706,Married,Accountant,3150,True

In [19]:
customers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       1000 non-null   int64
 1   first_name        1000 non-null   object
 2   last_name         1000 non-null   object
 3   gender            1000 non-null   object
 4   age               1000 non-null   int64
 5   email             1000 non-null   object
 6   phone             1000 non-null   object
 7   city              1000 non-null   object
 8   state             1000 non-null   object
 9   country           1000 non-null   object
 10  signup_date       1000 non-null   object
 11  customer_segment  1000 non-null   object
 12  annual_income     1000 non-null   int64
 13  marital_status    1000 non-null   object
 14  occupation        1000 non-null   object
 15  loyalty_points    1000 non-null   int64
 16  is_active         1000 non-null   bool
dtypes: bool(1), int64(4), object(12)
memory usage: 126.1+ KB

In [20]:
customers_df.isnull().sum()

customer_id         0
first_name          0
last_name           0
gender              0
age                 0
email               0
phone               0
city                0
state               0
country             0
signup_date         0
customer_segment    0
annual_income       0
marital_status      0
occupation          0
loyalty_points      0
is_active           0
dtype: int64

In [21]:
customers_df.to_csv(
    "../data/raw/customers.csv",
    index=False
)

print("customers.csv saved successfully!")

customers.csv saved successfully!

In [22]:
customers_df.describe()

       customer_id         age  annual_income  loyalty_points
count  1000.000000  1000.00000   1.000000e+03      1000.00000
mean    500.500000    44.74300   1.623898e+06      5016.64600
std     288.819436    15.16433   7.947111e+05      2836.10555
min       1.000000    18.00000   2.028660e+05        23.00000
25%     250.750000    31.00000   9.378145e+05      2525.00000
50%     500.500000    46.00000   1.643656e+06      4982.50000
75%     750.250000    58.00000   2.323417e+06      7497.75000
max    1000.000000    70.00000   2.997837e+06      9978.00000

In [23]:
customers_df.describe(include="object")

,first_name,last_name,gender,email,phone,city,state,country,signup_date,customer_segment,marital_status,occupation
count,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000
unique,454,448,2,1000,1000,306,28,1,780,4,2,10
top,Krishna,Chanda,Male,ekantikaprabhu@example.net,06472130742,Ghaziabad,Jharkhand,India,2022-03-09,Regular,Single,Doctor
freq,7,7,521,1,1,10,48,1000,4,275,532,110

In [24]:
customers_df["customer_segment"].value_counts()

customer_segment
Regular    275
Silver     265
Premium    243
GOld       217
Name: count, dtype: int64

In [25]:
customers_df["gender"].value_counts()

gender
Male      521
Female    479
Name: count, dtype: int64

In [26]:
customers_df["is_active"].value_counts()

is_active
False    532
True     468
Name: count, dtype: int64