In [1]:
import pandas as pd
import numpy as np
from faker import Faker
import random

In [2]:
fake = Faker("en_IN")

random.seed(42)
Faker.seed(42)

NUM_PRODUCTS = 500

print("Configuration Loaded Successfully!")
print(f"Products to Generate: {NUM_PRODUCTS}")

Configuration Loaded Successfully!
Products to Generate: 500

In [3]:
categories = [
    "Electronics",
    "Fashion",
    "Home & Kitchen",
    "Beauty",
    "Sports",
    "Books",
    "Toys",
    "Grocery"
]

brands = [
    "Samsung",
    "Apple",
    "Sony",
    "Nike",
    "Adidas",
    "Puma",
    "LG",
    "HP",
    "Dell",
    "Boat"
]

print("Categories Loaded Successfully!")

Categories Loaded Successfully!

In [4]:
def generate_product(product_id):

    return {
        "product_id": product_id,
        "product_name": fake.word().title(),
        "category": random.choice(categories),
        "brand": random.choice(brands),
        "price": random.randint(500, 100000),
        "rating": round(random.uniform(1, 5), 1),
        "stock": random.randint(10, 1000),
        "discount": random.randint(0, 50),
        "is_available": random.choice([True, False])
    }

In [5]:
product = generate_product(1)
product

{'product_id': 1,
 'product_name': 'Tempore',
 'category': 'Fashion',
 'brand': 'Samsung',
 'price': 97696,
 'rating': 2.1,
 'stock': 238,
 'discount': 8,
 'is_available': True}

In [6]:
products = []

for product_id in range(1, NUM_PRODUCTS + 1):
    products.append(generate_product(product_id))

print(f"Total Products Generated: {len(products)}")

Total Products Generated: 500

In [7]:
products_df = pd.DataFrame(products)

products_df.head()

,product_id,product_name,category,brand,price,rating,stock,discount,is_available
0,1,Culpa,Fashion,Boat,55802,1.1,105,13,True
1,2,Alias,Electronics,Dell,26562,3.9,728,34,False
2,3,Harum,Beauty,HP,77736,2.1,900,0,True
3,4,Exercitationem,Toys,Puma,36921,1.6,990,48,False
4,5,Et,Fashion,Apple,50297,1.4,877,22,False

In [8]:
products_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    500 non-null    int64
 1   product_name  500 non-null    object
 2   category      500 non-null    object
 3   brand         500 non-null    object
 4   price         500 non-null    int64
 5   rating        500 non-null    float64
 6   stock         500 non-null    int64
 7   discount      500 non-null    int64
 8   is_available  500 non-null    bool
dtypes: bool(1), float64(1), int64(4), object(3)
memory usage: 31.9+ KB

In [9]:
products_df.isnull().sum()

product_id      0
product_name    0
category        0
brand           0
price           0
rating          0
stock           0
discount        0
is_available    0
dtype: int64

In [10]:
products_df.to_csv(
    "../data/raw/products.csv",
    index=False
)

print("products.csv saved successfully!")

products.csv saved successfully!

In [11]:
products_df.describe()

       product_id         price      rating       stock    discount
count  500.000000    500.000000  500.000000  500.000000  500.000000
mean   250.500000  46825.930000    3.035800  517.706000   25.150000
std    144.481833  28702.406524    1.189693  287.461873   14.462289
min      1.000000    691.000000    1.000000   12.000000    0.000000
25%    125.750000  21225.750000    2.000000  259.000000   13.000000
50%    250.500000  46005.500000    3.100000  522.000000   25.000000
75%    375.250000  71130.750000    4.100000  748.750000   37.000000
max    500.000000  99451.000000    5.000000  999.000000   50.000000

In [12]:
products_df["category"].value_counts()

category
Fashion           80
Sports            69
Home & Kitchen    66
Toys              63
Books             63
Beauty            61
Grocery           52
Electronics       46
Name: count, dtype: int64

In [13]:
products_df["brand"].value_counts()

brand
HP         68
Dell       63
LG         57
Apple      53
Adidas     51
Puma       51
Nike       43
Sony       43
Boat       42
Samsung    29
Name: count, dtype: int64