In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [4]:
engine = create_engine(
    "mysql+pymysql://root:Monika%40123@localhost:3306/customer_intelligence_db"
)

In [5]:
customers = pd.read_sql("SELECT * FROM customers", engine)

customers.head()

,customer_id,first_name,last_name,gender,age,email,phone,city,state,country,signup_date,customer_segment,annual_income,marital_status,occupation,loyalty_points,is_active
0,1,Oni,Kannan,Female,20,zmall@example.org,+916542351161,Hapur,Punjab,India,2023-10-26,Premium,592986.0,Single,Business,8279,0
1,2,Caleb,Sharaf,Male,63,radhakrishnanfarhan@example.net,09593103413,Nadiad,Himachal Pradesh,India,2025-06-04,Regular,1124594.0,Married,Accountant,4557,0
2,3,Janya,Gaba,Male,62,isha34@example.net,1928327648,Anantapur,Uttarakhand,India,2022-01-16,Regular,1627114.0,Married,Teacher,3527,0
3,4,Veer,Balay,Male,23,nandini41@example.org,5376724238,Bhimavaram,Maharashtra,India,2026-07-13,Regular,605657.0,Married,Lawyer,9891,0
4,5,Mohini,Pathak,Male,64,lakshitupadhyay@example.com,+910122691669,Dehri,Himachal Pradesh,India,2026-04-10,Regular,2449103.0,Single,Designer,1291,0

In [6]:
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
customers = pd.read_sql("SELECT * FROM customers", engine)
products = pd.read_sql("SELECT * FROM products", engine)
orders = pd.read_sql("SELECT * FROM orders", engine)

In [8]:
print("Customers Shape:", customers.shape)
print("Products Shape:", products.shape)
print("Orders Shape:", orders.shape)

Customers Shape: (1000, 17)
Products Shape: (500, 9)
Orders Shape: (5000, 9)

In [9]:
print(customers.isnull().sum())
print(products.isnull().sum())
print(orders.isnull().sum())

customer_id         0
first_name          0
last_name           0
gender              0
age                 0
email               0
phone               0
city                0
state               0
country             0
signup_date         0
customer_segment    0
annual_income       0
marital_status      0
occupation          0
loyalty_points      0
is_active           0
dtype: int64
product_id      0
product_name    0
category        0
brand           0
price           0
rating          0
stock           0
discount        0
is_available    0
dtype: int64
order_id          0
customer_id       0
product_id        0
order_date        0
quantity          0
unit_price        0
total_amount      0
payment_method    0
order_status      0
dtype: int64

In [10]:
customers.describe()

       customer_id          age  annual_income  loyalty_points  is_active
count  1000.000000  1000.000000   1.000000e+03     1000.000000     1000.0
mean    500.500000    44.732000   1.624913e+06     5017.740000        0.0
std     288.819436    15.222546   7.933571e+05     2852.849544        0.0
min       1.000000    18.000000   2.028660e+05       23.000000        0.0
25%     250.750000    31.000000   9.485212e+05     2515.250000        0.0
50%     500.500000    46.000000   1.646552e+06     4963.500000        0.0
75%     750.250000    58.000000   2.322204e+06     7511.750000        0.0
max    1000.000000    70.000000   2.997837e+06     9978.000000        0.0

In [11]:
products.describe()

,product_id,price,rating,stock,discount,is_available
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.0
mean,250.500000,46825.930000,3.035800,517.706000,25.150000,0.0
std,144.481833,28702.406524,1.189693,287.461873,14.462289,0.0
min,1.000000,691.000000,1.000000,12.000000,0.000000,0.0
25%,125.750000,21225.750000,2.000000,259.000000,13.000000,0.0
50%,250.500000,46005.500000,3.100000,522.000000,25.000000,0.0
75%,375.250000,71130.750000,4.100000,748.750000,37.000000,0.0
max,500.000000,99451.000000,5.000000,999.000000,50.000000,0.0

In [12]:
orders.describe()

,order_id,customer_id,product_id,quantity,unit_price,total_amount
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,2500.500000,500.863200,251.227400,2.989400,46551.452800,139075.717000
std,1443.520003,289.974277,144.809387,1.401314,28641.273698,115547.818075
min,1.000000,1.000000,1.000000,1.000000,691.000000,691.000000
25%,1250.750000,248.000000,124.000000,2.000000,19668.000000,47847.000000
50%,2500.500000,503.500000,253.000000,3.000000,46218.000000,101104.000000
75%,3750.250000,750.000000,377.250000,4.000000,71075.000000,205083.000000
max,5000.000000,1000.000000,500.000000,5.000000,99451.000000,497255.000000

In [13]:
customers["customer_segment"].value_counts()

customer_segment
Regular    283
Silver     258
Premium    246
GOld       213
Name: count, dtype: int64

In [14]:
orders["total_amount"].describe()

count      5000.000000
mean     139075.717000
std      115547.818075
min         691.000000
25%       47847.000000
50%      101104.000000
75%      205083.000000
max      497255.000000
Name: total_amount, dtype: float64

In [15]:
orders.sort_values(by="total_amount", ascending=False).head(10)

,order_id,customer_id,product_id,order_date,quantity,unit_price,total_amount,payment_method,order_status
808,809,73,207,2026-03-02,5,99451.0,497255.0,Debit Card,Delivered
4265,4266,176,207,2024-12-11,5,99451.0,497255.0,UPI,Returned
1231,1232,496,207,2024-10-23,5,99451.0,497255.0,UPI,Delivered
167,168,867,334,2025-08-14,5,99296.0,496480.0,Net Banking,Shipped
692,693,72,47,2024-07-28,5,99048.0,495240.0,UPI,Shipped
3865,3866,736,47,2025-04-02,5,99048.0,495240.0,Debit Card,Shipped
2125,2126,537,47,2024-12-14,5,99048.0,495240.0,UPI,Delivered
2566,2567,701,338,2026-05-03,5,98507.0,492535.0,Debit Card,Cancelled
1174,1175,567,338,2024-12-23,5,98507.0,492535.0,UPI,Returned
3443,3444,339,338,2025-11-07,5,98507.0,492535.0,Net Banking,Returned

In [16]:
sales = (
    orders.merge(customers, on="customer_id", how="inner")
          .merge(products, on="product_id", how="inner")
)

sales.head()

,order_id,customer_id,product_id,order_date,quantity,unit_price,total_amount,payment_method,order_status,first_name,...,loyalty_points,is_active,product_name,category,brand,price,rating,stock,discount,is_available
0,1,56,215,2024-10-21,2,57740.0,115480.0,Credit Card,Shipped,Gunbir,...,7043,0,Nulla,Books,Apple,57740.0,4.4,259,27.0,0
1,2,589,381,2024-08-15,1,52522.0,52522.0,Cash on Delivery,Delivered,Bina,...,6178,0,Dolore,Books,Adidas,52522.0,1.3,992,25.0,0
2,3,288,72,2026-02-22,5,80016.0,400080.0,Net Banking,Delivered,Viraj,...,3692,0,Odit,Toys,Boat,80016.0,3.6,486,28.0,0
3,4,765,25,2025-02-25,1,16983.0,16983.0,UPI,Shipped,Abdul,...,1827,0,Quisquam,Fashion,Dell,16983.0,1.5,496,35.0,0
4,5,643,418,2025-02-02,2,6356.0,12712.0,Cash on Delivery,Delivered,Bhavna,...,8873,0,Aperiam,Fashion,Adidas,6356.0,4.2,127,1.0,0

In [17]:
sales.shape

(5000, 33)

In [18]:
total_revenue = sales["total_amount"].sum()
print(f"Total Revenue: ₹{total_revenue:,.2f}")

Total Revenue: ₹695,378,585.00

In [19]:
print("Total Customers:", sales["customer_id"].nunique())

Total Customers: 994

In [20]:
print("Total Quantity Sold:", sales["quantity"].sum())

Total Quantity Sold: 14947

In [21]:
print(f"Average Order Value: ₹{sales['total_amount'].mean():,.2f}")

Average Order Value: ₹139,075.72

In [22]:
top_customers = (
    sales.groupby(["customer_id", "first_name", "last_name"], as_index=False)
         .agg(
             Revenue=("total_amount", "sum"),
             Orders=("order_id", "count")
         )
         .sort_values("Revenue", ascending=False)
         .head(10)
)

top_customers

     customer_id first_name   last_name    Revenue  Orders
15            16   Nachiket       Magar  2394223.0       9
930          937      Nirja        Dass  2291913.0      14
561          567     Mahika        Raju  2281390.0      11
897          904   Aradhana      Vaidya  2089300.0      10
107          109     Ojasvi       Sinha  1990185.0       9
910          917     Zehaan      Taneja  1908478.0       8
243          247    Harshil    Chandran  1905769.0      10
978          985        Sai  Contractor  1903277.0       7
246          250    Abhiram       Swamy  1872067.0      11
92            93    Vasudha       Konda  1857658.0       7

In [23]:
top_products = (
    sales.groupby(["product_id", "product_name"], as_index=False)
         .agg(
             Quantity_Sold=("quantity", "sum"),
             Revenue=("total_amount", "sum")
         )
         .sort_values("Revenue", ascending=False)
         .head(10)
)

top_products

     product_id product_name  Quantity_Sold    Revenue
311         312        Eaque             74  5967878.0
279         280     Officiis             60  5378580.0
319         320   Aspernatur             51  5021205.0
87           88    Quibusdam             45  4431510.0
246         247          Rem             54  4382316.0
46           47         Fuga             44  4358112.0
44           45      Laborum             50  4333150.0
464         465        Neque             62  4238444.0
333         334       Veniam             42  4170432.0
188         189    Excepturi             44  4130500.0